#!/bin/bash
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        #  run functions
#------------------------------------------------------------------------------

#remove previous data and logs
rm -rf dynamicCode processor* postProcessing log* runLog*

# run blockMeshDict
runApplication blockMesh 2>&1 
# run topoSetDict
runApplication topoSet 2>&1 


echo End

#------------------------------------------------------------------------------
