#!/bin/bash
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        #  run functions
#------------------------------------------------------------------------------

#run the simulation
srun -n 96 epotMultiRegionInterFoam -parallel 2>&1 | tee ./runLog

#------------------------------------------------------------------------------
